# Permalinks
#
permalink:           pretty
markdown:            kramdown

# Setup
title:               islr
tagline:             ''
description:         'Notes and exercises from Introduction to Statistical Learning'
url:                 127.0.0.1:4000
baseurl:             /islr

# About/contact
author:
  name:              Ryan Wenzel
  url:               https://rmwenzel.com
  email:             rmwenzel@uw.edu


plugins:
  - jekyll-katex